FROM apache/airflow:2.3.3

# Copy the requirements.txt file and install dependencies
COPY requirements.txt /opt/airflow/requirements.txt
COPY etl_dag.py ${AIRFLOW_HOME}/dags/etl_dag.py
RUN pip install -r /opt/airflow/requirements.txt
